spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/guardian_payment}
spring.datasource.username=${DB_USERNAME:guardian}
spring.datasource.password=${DB_PASSWORD:guardian}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8083

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer